#include "constants.h"


#define SLEEP DISABLED
#define DEEP_SLEEP DISABLED
#define LIGHT_SLEEP_DUR_S 120
#define DEEP_SLEEP_DUR_S 600

#define BENCHMARK DISABLED
#define ONE_PER_SEC (1000UL)
#define TEN_PER_SEC (100UL)
#define ONE_HUNDRED_PER_SEC (10UL)
#define LOW_LOAD_DEL_MS ONE_PER_SEC
#define MED_LOAD_DEL_MS TEN_PER_SEC
#define HIGH_LOAD_DEL_MS ONE_HUNDRED_PER_SEC