@startuml wireless-transmitter-2.0

package wireless_shared{
    folder wifi{
        file wifi.h
        file msg_types.h
    }
    folder src{
        file wifi.c
    }
    file constants.h
}

folder main{
    folder devices{
        file devices.h
        file keyboard.c
        file mouse.c
        file gamepad.c
    }
    folder hardware{
        file hardware.h
        file hardware.c
    }
    folder sleep{
        file sleep.h
        file sleep.c
    }
    file main.c
    file device_config.h
}

main --> wireless_shared
hardware --> devices
hardware --> sleep
main.c --> hardware

@enduml