@startuml wireless-receiver-2.0

package wireless_shared{
    file constants.h
    folder wifi{
        file wifi.h
        file msg_types.h
    }
    folder src{
        file wifi.c
    }
}

folder main{
    folder devices{
        file devices.h
        file devices.c
        file keyboard.c
        file keyboard.h
        file mouse.c
        file mouse.h
    }

    folder hardware{
        file hardware.h
        file hardware.c
    }

    folder tusb{
        file tusb_cb.c
        file tusb_config.h
        file tusb_device_common.h
    }
    file main.c
    file device_config.h
}

main.c-->hardware
main.c-->devices

main-->wireless_shared

@enduml